### PR TITLE
kwargs for enabling compression on datasets in emd files.

### PR DESCRIPTION
**Pull request by ZGainsforth**
A user can pass in compression or any other kwargs to create_dataset() if he wants to.

### CODE REVIEW

**Comment by ercius** [comment]
@ZGainsforth Can you add the **kwargs to the docstring? Then users will know that they can pass additional parameters to h5py.create_dataset.

**Comment by ZGainsforth** [comment]
Done.

**Comment by ercius** [comment]
Thanks for getting this added!

**Comment by ZGainsforth** [comment]
You’re welcome!

**Pull request merged**
