### PR TITLE
Pull request for EDS tomo awesomeness

### PR DESCRIPTION
**Pull request by ZGainsforth**
Hi Peter,

Here we go!  This is the first version.  I did quite a bit of refactoring and expansion of the original code that was on atlassian.  Now it is much more modular and useful.  I made a jupyter notebook example and included a sample dataset so a new user can walk through the notebook and see how it works.

Also, we should discuss in the future whether it makes sense to put files in the data directory on  git-lfs.  On one hand they are big.  On the other hand, they aren't changing that much.

More to come later, and I'll be up next week too so we can talk.

Cheers,

Zack

### CODE REVIEW

**Comment by ZGainsforth** [comment]
Hi Peter,

Updated to make edstomo an optional submodule.  That way it does not automatically install all the dependencies unless the user requests.

**Comment by ercius** [comment]
@ZGainsforth  It would be great to add some information about this module to the openncem README (under components? or make a new heading?) and the ncempy README (how to install it; indicate its optional).

**Comment by ZGainsforth** [comment]
I did, but it is in the README.rst under ncempy which describes the individual components of ncempy.  It's not in the README.rst in the root.  Perhaps we want to consolidate those?

**Comment by ercius** [comment]
Well, openNCEM is supposed to encompass more than just ncempy. There are some tools and potentially some other packages which could be kept under openNCEM. Lets keep it as is with your additions to the ncempy README and not add anything to the openNCEM README.

There are some conflicts the the .gitignore. That should be easy to clean up.

**Comment by ercius** [comment]
@ZGainsforth It is merged! Thanks for all your work on this. Its great to have EDS tomography working in ncempy.

**Comment by ZGainsforth** [comment]
Super!  It is exciting.  Now I can pull and start processing my tomo stacks.  ;-)

Zack

**Pull request merged**
